import type { Metadata } from "next";
import { MantineProvider } from "@mantine/core";
import { HIITProvider } from "./utils/useHIITContext";
import '@mantine/core/styles.css'

export const metadata: Metadata = {
  title: "Workout timer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider defaultColorScheme="dark">
          <HIITProvider>
            {children}
          </HIITProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
